version: '0.0.1'
services:
  trickfarmserver:
    image: "trickfarmserver"
    build:
      context: .
      dockerfile: TrickFarmServer/Dockerfile
    ports:
      - "5000:5000"
      - "8080:8080"
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - REDIS_CONNECTION_STRING=redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    container_name: redis_server
    ports:
      - "6379:6379"