version: '3.8'
services:
  redis:
    image: "redis:latest"
    container_name: redis_server

  trickfarmserver:
    image: "trickfarmserver"
    build:
      context: .
      dockerfile: TrickFarmServer/Dockerfile
    ports:
      - "5000:5000"
      - "8080:8080"
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - REDIS_CONNECTION_STRING=redis:6379
    depends_on:
      - redis

  trickfarmwebapp:
    image: "trickfarmwebapp"
    build:
      context: .
      dockerfile: TrickFarmWebApp/TrickFarmWebApp/Dockerfile
    ports:
      - "53502:53502"
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_URLS=http://0.0.0.0:53502
    depends_on:
      - trickfarmserver
    volumes:
      - ./dataprotection:/app/dataprotection-keys
